### ISSUE TITLE
Scrolling is buggy 

### ISSUE THREAD

**Issue by EndLess728** [LiewJunTung/alphabet_list_scroll_view#2]
Scrolling is buggy in this lib. Please have a look at it.

Sometimes when I Scroll over widget list the scrolling doesn't work. I have to move my hands on it 2 or 3 times to scroll over it.

**Comment by LiewJunTung** [comment]
Noted, I'll check it out

**Comment by LiewJunTung** [comment]
Caught it!

**Comment by EndLess728** [comment]
> Caught it!

I guess you figured it out , i am waiting for the update . Thanks

**Comment by EndLess728** [comment]
Ohh just saw the update, Thanks Budy

**Comment by LiewJunTung** [comment]
Thanks for reporting!
